networks:
  streamlitGPT:
    name: streamlitGPT
    driver: bridge

x-ollama: &service-ollama
  image: ollama/ollama:latest
  container_name: ollama
  networks: ['streamlitGPT']
  restart: unless-stopped
  ports:
    - 11434:11434

x-init-ollama: &init-ollama
  image: ollama/ollama:latest
  networks: ['streamlitGPT']
  container_name: ollama-pull-llama
  entrypoint: /bin/sh
  environment:
    - OLLAMA_HOST=ollama:11434
  command: 
    - "-c"
    - "sleep 3; ollama pull gpt-oss:20b"

services:
  ollama-cpu:
    profiles: ["cpu"]
    <<: *service-ollama

  ollama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *service-ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-pull-llama-cpu:
    profiles: ["cpu"]
    <<: *init-ollama
    depends_on:
      - ollama-cpu
  
  ollama-pull-llama-gpu:
    profiles: ["gpu-nvidia"]
    <<: *init-ollama
    depends_on:
      - ollama-gpu